### ISSUE TITLE
No custom counters available for Memory Group By on GCP DataFlow Web UI

### ISSUE THREAD

**Issue by diethardsteiner** [mattcasters/kettle-beam-core#10]
As a developer I'd like to have a **custom counter** available for the **memory group by** step, just like it is for other steps. The attached screenshot shows that it is currently missing:
![screenshot from 2018-12-09 20-54-06](https://user-images.githubusercontent.com/1726057/49702830-02f57480-fbf5-11e8-8b3d-b338bf83a353.png)

**Comment by mattcasters** [comment]
Actually, it's been added in the mean time.  Check the test for group by:

```
Name: MetricName{namespace=read, name=Group By} Attempted: 100 Committed: 100
Name: MetricName{namespace=init, name=Group By} Attempted: 12 Committed: 12
```

**Comment by mattcasters** [comment]
I've added more specific counters in the actual "group by" aggregation function to capture input and output:

Name: MetricName{namespace=written, name=Group By AGG} Attempted: 47 Committed: 47
Name: MetricName{namespace=read, name=Group By AGG} Attempted: 47 Committed: 47
Name: MetricName{namespace=init, name=Group By AGG} Attempted: 12 Committed: 12

So stepname +" AGG"

**Comment by mattcasters** [comment]
Actually that's technically correct but practically useless. It counts the groups, not the rows.

**Comment by mattcasters** [comment]
This is better
```
Name: MetricName{namespace=init, name=Group By AGG} Attempted: 12 Committed: 12
Name: MetricName{namespace=read, name=Group By AGG} Attempted: 100 Committed: 100
Name: MetricName{namespace=written, name=Group By AGG} Attempted: 47 Committed: 47
```

**Comment by diethardsteiner** [comment]
Excellent, thanks a lot!
